before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: AqZYlidPP7e0j4RT3haUtKCDzAgDeAUuozq7GqooTLsOOiwu8EhRKKCwjt/gcXVY1fQvSgO+jxinPMKy8xjdbnNXLT+VyxOSd9HC2wtKJExaR40nfToHm/5v0+8rGJCtbr/x88X78OAk1h8KFEExLKHsLIIWRI7DznpMDWrWq5apQPO3Tefn12V4rP05xmJFFOSl3IrmIhKmLmY1YHWcyw9MAA51f+/zB8LoZzg5Ay4BbZsDv9bjtqTG+SfYh8adQePdbUMuBx15M11OPMiKup5cJlV0MHQGXMznrUfh0eUJm+7IAfIFvAuDLhXd3C8+byZ1PiwrNd0f/TcGb6Z6OhvEacOiRc9nMM7iPZ9QFb6fkW4CX00ikQ+rs9x/bHgeb0sb9DiwjqhJlU1vZcKhfDppTqvC62072d0CSXokXzxZOWVa54/tQRHtYDbstLk9g56xKy+o1RAo5DrMi7pAz1td3K3IioEdGvz5Bg+mIwk2P5daAv2hCJKZ1HMJO/UsR60JBqOt7wWiexh7QenyW5IXc0yNWmVNhLoxvhghXL+BWRxJG9roPBc6EzSstMH/7srGa5UWhrfUGZd8/S0IlHinhbby146E6k3CJZM964zKka5seXw2RvP/JNxCz3SA5nZIqXv6a5A5JTfm2NfnJwtNLTx8okvqlORx4RKtgjM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
